# Generated by Django 5.1.7 on 2025-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
